### ISSUE TITLE
Feature: Support for offline players/UUIDs

### ISSUE THREAD

**Issue by BrainStone** [FTBTeam/FTB-Money#12]
It would be nice to be able to manipulate and retrieve the money of offline players. Preferably identified by UUIDs (makes using the interface easier).

The reasoning behind that is that it would allow players to receive money while they are offline. Examples when this is useful include: Vote rewards, passive income, being paid while offline.

**Comment by BrainStone** [comment]
Any updates on this? (Just curious, no rush)

**Comment by LatvianModder** [comment]
I will most likely merge FTB Money into FTB Quests by end of month, so then it will also support offline money

**Comment by BrainStone** [comment]
That's ok in my book. Would you mind to update this issue then again?

**Comment by BrainStone** [comment]
Any updates? I just today received a request to add support, but this is a blocker for me.

**Comment by Jeffmagma** [comment]
I also think this is a good idea as I was thinking of adding a shops system to a server but so far people cannot be paid unless they are online
