### ISSUE TITLE
Money resets when entering different dimensions

### ISSUE THREAD

**Issue by AchdFTW** [FTBTeam/FTB-Money#17]
My friends and I were playing on a server which has the Roguelike Adventures and Dungeons modpack and everytime we enter a different dimension the money goes to 0

**Comment by megoesrawr** [comment]
This is still happening :/

**Comment by TerdyTheTerd** [comment]
I fixed this in my fork, I did a very basic fix and did some basic testing, everything seemed to work, but I cannot guarantee that there won't be unexpected issues later on. If you do not know how to compile a mod from a repo, create an issue on my fork and if the license allows it I will put a release file on my fork.
