### ISSUE TITLE
Crash on shop creation

### ISSUE THREAD

**Issue by TheQKnight** [FTBTeam/FTB-Money#21]
I have a few other mods installed, but vanillafix says its a conflict between ftb money and lib.
Im using the latest version of both mods.

https://paste.dimdev.org/hojinumoci.mccrash

**Comment by mpztilera** [comment]
I have the same issue

**Comment by mpztilera** [comment]
It looks like "file" in Shop.java is always null

**Comment by mpztilera** [comment]
For anyone else, who gets this error, just take the last FTBLib version from 2019
