### ISSUE TITLE
Cannot buy osmium (from Mekanism) in the shop (modpack = MC Eternal 1.3.4)

### ISSUE THREAD

**Issue by Abramor** [FTBTeam/FTB-Money#23]
Hello, 
I play on a MC Eternal (1.3.4) server that I made and even if the shop tell me that I can buy osmium (from the mod Mekanism) it do not take my money nor buy the osmium.
For the other item the shop work perfectly.
Thanks for your help.

**Comment by isambourgg** [comment]
Hello ! 
Same problem here.
I play on dedicaced server : MC Eternal (1.3.5b) - Forge-14.23.5.2847 - FTBMoney-1.1.0.42
Its strange because i have buy osmium ingot and few hours later, the bug has appear.
I have the log entry if necessary.
Good luck !

**Comment by EpicCraft1997** [comment]
edit it and remove the requirements fixed it for me

**Comment by CasuallyCode** [comment]
@EpicCraft1997 Can you please elaborate? I've been playing MC Eternal Lite and have the same issue where in the shop section of the quest book I'm supposed to be able to buy 3 osmium ingots for 450 coins but am simply not able to (no coins are deducted and no items are added to my inventory) despite it showing up as a valid purchase in the shop. I'd love to know how you fixed this bug.

**Comment by Ne0nhigh** [comment]
same issue here. I play Eternal 1.3.6 

hope someone can help

**Comment by Xplodin** [comment]
> same issue here. I play Eternal 1.3.6
> 
> hope someone can help or @EpicCraft1997 can you explain me how you fixed it ?

He just did.
Remove the quest requirements for the shop item.
MCE is a buggy pack
