### ISSUE TITLE
When trying to add item to shop

### ISSUE THREAD

**Issue by mac2040** [FTBTeam/FTB-Money#3]
https://pastebin.com/s6GE54i2

**Comment by kreezxil** [comment]
confirmed client crash while trying to add item to shop system in ftb quests.

forge build 2796
https://pastebin.com/YUJgVgVS

**Comment by pyure** [comment]
@LatvianModder do we have a temporary workaround on this?  How do users currently tweak the shop?

**Comment by Agrax** [comment]
@pyure developers* :P

https://pastebin.com/g5TV6M56

My 0,02$. If it's a common error it should probably be fixed, coz adding items to the shop is like the essential part of it :P
