### ISSUE TITLE
SetMoney Add/Sub parameter

### ISSUE THREAD

**Issue by MeinKraft** [FTBTeam/FTB-Money#30]
Hello,  Could you please add an extra parameter to the setmoney command? So we can Add or Sub money from the players total,

`/setmoney @s 100 sub`  would subtract 100 from the player
`/setmoney @s 100 add`  would add 100 to the player
`/setmoney @s 100` would set the players total to 100

instead of how it currently works, by only changing the `total` the player has

example: Clearing out a LostCities building would enable me to run a command to add money to the players total

Thank you

**Comment by GoDzViper** [comment]
Would love to see this too!

**Comment by LatvianModder** [comment]
like `/setmoney @s ~100`? 🤔
